### ISSUE TITLE
Logo is unbalanced

### ISSUE THREAD

**Issue by chris-morgan** [actix/actix-website#18]
Tossed up where to file this, settled on here. This is a somewhat lighthearted report, but nonetheless a serious issue for the two or three of us who care about such matters. ☺

The Actix logo is not balanced. If you cut it in metal and used it for the sprocket on a bicycle, it would fail dismally.

This is probably most easily demonstrated by supercharging the spinning of the logo on the website:

```css
.navbar-brand img {
	/* The forties are for forty teeth, the 60 for 60fps. */
	animation: spin-logo calc(40s/60) steps(40) infinite;
	/* While we’re at it, let’s make it as big as we can. */
	width: 100vmin;
	height: auto;
	top: calc(50vh - 50vmin);
	left: calc(50vw - 50vmin);
	position: fixed;
	z-index: 1;
	/* You might like to play around with this too, to mitigate some of the image centrepoint unbalancedness: */
	/* transform-origin: 49% 50%; */
}
```

As you observe, the image is not centred properly, and the teeth are irregularly cut because they’re not aligned with the rest.

The logo should have a fixed centre point about which it rotates, rotational symmetry on its teeth (40-way if it must have 40 teeth—for reference, the Rust logo has 32, and I recommend 48 for Actix to factor neatly into the three-way rotational symmetry), and three-way rotational symmetry on the inner portion.

I’m willing to produce a new, mathematically-sound logo if you want (my approach on the teeth is to use Inkscape’s Pattern Along Path live path effect). I still won’t guarantee it will work as a sprocket, especially if it stays fairly similar in the tooth design. Is there an SVG source for the current logo, for mild convenience? (I observe [logo.afdesign](https://github.com/actix/actix-website/blob/master/artwork/logo.afdesign), but I have nothing that can open that file type.)
