### ISSUE TITLE
please preserve my eyesight and add a dark mode

### ISSUE THREAD

**Issue by firstdorsal** [actix/actix-website#243]
just add a media query in your css like this (i put this together in a few minutes using stylebot):

```css

@media (prefers-color-scheme: dark) {
  html body {
  background: #111;
  color:white;
}

div.actix-showcase {
  background-color: #333;
}

a.nav-link,li.active * {
  color:cornflowerblue !important;
}

pre,p code {
  background: #222;
  color:white;
}

li.active  {
  background: #222;
}

/* 
you can strip out these by just choosing another code theme that is dark mode compatible
*/
span.s {
  color: green !important;
}

span.k {
  color:violet !important;
} 

span.sd,span.cp {
  color: #888 !important;
}

span.kt {
  color:red !important;
}

span.nf{
  color:dodgerblue !important;
}

span.nc,span.nb {
  color:gold !important;
}


}
```
